# Generated by Django 4.2.1 on 2024-02-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_about_me_user_grade_user_programming_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='programming_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
    ]
