# Generated by Django 4.2.1 on 2024-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='default_avatar/photo_net.png', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
