# Generated by Django 4.2.1 on 2024-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_first_name_alter_user_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior'), ('Lead', 'Lead')], default='Beginner', max_length=10, verbose_name='Разряд'),
        ),
    ]
