# Generated by Django 4.2.1 on 2024-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_channelnames_first_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default='False'),
        ),
    ]
