# Generated by Django 4.2.1 on 2024-03-13 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_message_options_remove_message_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.TextField()),
                ('first_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user_id', to=settings.AUTH_USER_MODEL)),
                ('second_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
