# Generated by Django 4.2.1 on 2024-03-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_channelnames_first_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelnames',
            old_name='first_user_id',
            new_name='first_user',
        ),
        migrations.RenameField(
            model_name='channelnames',
            old_name='second_user_id',
            new_name='second_user',
        ),
    ]
