# Generated by Django 4.2.1 on 2024-03-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelnames',
            name='channel_messages',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='chat.message'),
        ),
    ]
