# Generated by Django 4.2.1 on 2024-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_channelnames_channel_messages_message_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
