# Generated by Django 4.2.1 on 2024-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0002_alter_like_comment_like_alter_like_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo_content',
            field=models.ImageField(default='NULL', null=True, upload_to='posts/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d/'),
        ),
    ]
