# Generated by Django 4.2.1 on 2024-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0004_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='photo_content',
        ),
        migrations.AddField(
            model_name='posts',
            name='code_content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
