# Generated by Django 4.2.1 on 2024-03-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0005_remove_posts_photo_content_posts_code_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='code_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
