# Generated by Django 4.2.1 on 2024-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0006_alter_posts_code_content_alter_posts_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='output_content',
            field=models.TextField(null=True),
        ),
    ]
