# Generated by Django 4.2.1 on 2024-03-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='ribbon.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='ribbon.posts'),
        ),
    ]
