# Generated by Django 4.2.1 on 2024-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ribbon', '0003_alter_posts_photo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Null'),
        ),
    ]
